
packages:
  - name: apisyncvideos
    parameters: # package scope
    environment:
    functions:
      - name: apisyncvideos
        parameters: # function scope
        environment:
          MONGODB_URI: "${MONGODB_URI}"
          TRANSLATE_API_KEY: "${TRANSLATE_API_KEY}"
        limits:
          timeout: 900000 # tempo máximo em milissegundos (15 min)
          memory: 256MiB
        runtime: 'nodejs:default'
        main: './pages/api/videos/syncronize/index.js'