

packages:
  - name: narrativa-manager
    # environment:
    #     MONGODB_URI: "${MONGODB_URI}"
    #     TRANSLATE_API_KEY: "${TRANSLATE_API_KEY}"
    #     YOUTUBE_API_KEY: "${YOUTUBE_API_KEY}"
    actions:
      - name: scheduled
        limits:
          memory: 896
          timeout: 600000
        runtime: 'python:3.11'
      - name: legenda
        limits:
          memory: 896
          timeout: 600000
        runtime: 'python:3.11'