

packages:
  - name: narrativa-manager
    functions:
      - name: scheduled
        environment:
          REDIS_USER: __USUARIO__
          REDIS_PASSWORD: __SENHA__
        binary: false
        runtime: 'python:default'
        web: false
        limits:
          timeout: 600000
        triggers:
          - name: trigger-sync
            sourceType: scheduler
            sourceDetails:
              cron: "0 */6 * * *"
            
