

packages:
  - name: narrativa-manager
    functions:
      - name: scheduled
        binary: false
        runtime: 'python:default'
        web: false
        limits:
          timeout: 600000
        triggers:
          - name: trigger-sync
            sourceType: scheduler
            sourceDetails:
              cron: "0 */12 * * *"
